# Generated by Django 4.1.3 on 2022-12-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_album_num_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Album name'),
        ),
    ]
