# Generated by Django 4.1.3 on 2022-12-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_person_dress_name_person_dress_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='lastname_name',
            new_name='last_name',
        ),
    ]
